states = {'state_1': {'name': 'Delaware', 'capital': 'Dover', 'population': 990837, 'flower': 'peach blossom',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_1.jpg'},
		'state_2': {'name': 'Pennsylvania', 'capital': 'Harrisburg', 'population': 13011844, 'flower': 'mountain laurel',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_2.jpg'},
		'state_3': {'name': 'New Jersey', 'capital': 'Trenton', 'population': 9288994, 'flower': 'common blue violet',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_3.jpg'},
		'state_4': {'name': 'Georgia', 'capital': 'Atlanta', 'population': 10711908, 'flower': 'cherokee rose',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_4.jpg'},
		'state_5': {'name': 'Conneticut', 'capital': 'Hartford', 'population': 3605944, 'flower': 'mountain laurel',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_5.jpg'},
		'state_6': {'name': 'Massachusetts', 'capital': 'Boston', 'population': 7033469, 'flower': 'mayflower',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_6.jpg'},
		'state_7': {'name': 'Maryland', 'capital': 'Annapolis', 'population': 6185278, 'flower': 'black-eyed susan',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_7.jpg'},
		'state_8': {'name': 'South Carolina', 'capital': 'Columbia', 'population': 5124712, 'flower': 'yellow jessamine',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_8.jpg'},
		'state_9': {'name': 'New Hampshire', 'capital': 'Concord', 'population': 1377529, 'flower': 'purple lilac',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_9.jpg'},
		'state_10': {'name': 'Virginia', 'capital': 'Richmond', 'population': 8654542, 'flower': 'flowering dogwood',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_10.jpg'},
		'state_11': {'name': 'New York', 'capital': 'Albany', 'population': 20215751, 'flower': 'rose',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_11.jpg'},
		'state_12': {'name': 'North Carolina', 'capital': 'Raleigh', 'population': 10453948, 'flower': 'flowering dogwood',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_12.jpg'},
		'state_13': {'name': 'Rhode Island', 'capital': 'Providence', 'population': 1098163, 'flower': 'common blue violet',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_13.jpg'},
		'state_14': {'name': 'Vermont', 'capital': 'Montpelier', 'population': 643503, 'flower': 'red clover',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_14.jpg'},
		'state_15': {'name': 'Kentucky', 'capital': 'Frankfort', 'population': 4509342, 'flower': 'goldenrod',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_15.jpg'},
		'state_16': {'name': 'Tennessee', 'capital': 'Nashville', 'population': 6916897, 'flower': 'iris',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_16.jpg'},
		'state_17': {'name': 'Ohio', 'capital': 'Columbus', 'population': 11799448, 'flower': 'carnation',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_17.jpg'},
		'state_18': {'name': 'Louisiana', 'capital': 'Baton Rouge', 'population': 4657757, 'flower': 'magnolia',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_18.jpg'},
		'state_19': {'name': 'Indiana', 'capital': 'Indianapolis', 'population': 6785528, 'flower': 'peony',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_19.jpg'},
		'state_20': {'name': 'Mississippi', 'capital': 'Jackson', 'population': 2963914, 'flower': 'magnolia',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_20.jpg'},
		'state_21': {'name': 'Illinois', 'capital': 'Springfield', 'population': 12812508, 'flower': 'violet',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_21.jpg'},
		'state_22': {'name': 'Alabama', 'capital': 'Montgomery', 'population': 5024279, 'flower': 'camellia',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_22.jpg'},
		'state_23': {'name': 'Maine', 'capital': 'Augusta', 'population': 1344212, 'flower': 'white pine cone',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_23.jpg'},
		'state_24': {'name': 'Missouri', 'capital': 'Jefferson City', 'population': 6160281, 'flower': 'white hawthorn',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_24.jpg'},
		'state_25': {'name': 'Arkansas', 'capital': 'Little Rock', 'population': 3013756, 'flower': 'apple blossom',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_25.jpg'},
		'state_26': {'name': 'Michigan', 'capital': 'Lansing', 'population': 10077331, 'flower': 'apple blossom',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_26.jpg'},
		'state_27': {'name': 'Florida', 'capital': 'Tallahassee', 'population': 21538187, 'flower': 'orange blossom',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_27.jpg'},
		'state_28': {'name': 'Texas', 'capital': 'Austin', 'population': 29145505, 'flower': 'bluebonnet',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_28.jpg'},
		'state_29': {'name': 'Iowa', 'capital': 'Des Moines', 'population': 3190369, 'flower': 'prairie rose',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_29.jpg'},
		'state_30': {'name': 'Wisconsin', 'capital': 'Madison', 'population': 5893718, 'flower': 'wood violet',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_30.jpg'},
		'state_31': {'name': 'California', 'capital': 'Sacramento', 'population': 39538223, 'flower': 'california poppy',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_31.jpg'},
		'state_32': {'name': 'Minnesota', 'capital': 'Saint Paul', 'population': 5707390, 'flower': 'pink-and-white lady\'s slipper',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_32.jpg'},
		'state_33': {'name': 'Oregon', 'capital': 'Salem', 'population': 4237256, 'flower': 'oregon grape',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_33.jpg'},
		'state_34': {'name': 'Kansa', 'capital': 'Topeka', 'population': 2940865, 'flower': 'wild sunflower',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_34.jpg'},
		'state_35': {'name': 'West Virginia', 'capital': 'Charleston', 'population': 1793716, 'flower': 'rhododendron',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_35.jpg'},
		'state_36': {'name': 'Nevada', 'capital': 'Carson City', 'population': 3104614, 'flower': 'sagebrush',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_36.jpg'},
		'state_37': {'name': 'Nebraska', 'capital': 'Lincoln', 'population': 1961504, 'flower': 'tall goldenrod',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_37.jpg'},
		'state_38': {'name': 'Colorado', 'capital': 'Denver', 'population': 5773714, 'flower': 'rocky mountain columbine',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_38.jpg'},
		'state_39': {'name': 'North Dakota', 'capital': 'Bismarck', 'population': 779094, 'flower': 'wild prairie rose',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_39.jpg'},
		'state_40': {'name': 'South Dakota', 'capital': 'Pierre', 'population': 886667, 'flower': 'american pasque',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_40.jpg'},
		'state_41': {'name': 'Montana', 'capital': 'Helena', 'population': 1085407, 'flower': 'bitterroot',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_41.jpg'},
		'state_42': {'name': 'Washington', 'capital': 'Olympia', 'population': 7705281, 'flower': 'pacific rhododendron',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_42.jpg'},
		'state_43': {'name': 'Idaho', 'capital': 'Boise', 'population': 1839106, 'flower': 'syringa',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_43.jpg'},
		'state_44': {'name': 'Wyoming', 'capital': 'Cheyenne', 'population': 576850, 'flower': 'wyoming indian paintbrush',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_44.jpg'},
		'state_45': {'name': 'Utah', 'capital': 'Salt Lake City', 'population': 3271616, 'flower': 'sego lily',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_45.jpg'},
		'state_46': {'name': 'Oklahoma', 'capital': 'Oklahoma City', 'population': 3963516, 'flower': 'oklahoma rose',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_46.jpg'},
		'state_47': {'name': 'New Mexico', 'capital': 'Santa Fe', 'population': 2120220, 'flower': 'yucca',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_47.jpg'},
		'state_48': {'name': 'Arizona', 'capital': 'Phoenix', 'population': 7151502, 'flower': 'saguaro',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_48.jpg'},
		'state_49': {'name': 'Alaska', 'capital': 'Juneau', 'population': 736081, 'flower': 'forget-me-not',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_49.jpg'},
		'state_50': {'name': 'Hawaii', 'capital': 'Honolulu', 'population': 1455271, 'flower': 'pua aloalo',
		'image': 'C:\\Users\\hayes\\OneDrive\\Desktop\\Code\\SDEV300\\Week3\\chayes_wk3_lab_photos\\state_50.jpg'}}